name: "Gree Logix"

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: greelogix-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - greelogix-network

  # Application Laravel (PHP-FPM)
  app:
    container_name: greelogix-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: greelogix
        uid: 1000
    image: greelogix
    restart: unless-stopped
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - greelogix-network
    command: >
      sh -c "composer install &&
             php artisan key:generate &&
             php artisan migrate --force &&
             php-fpm"

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: greelogix-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - greelogix-network

  #  phpMyAdmin (optionnel)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: greelogix-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - greelogix-network

networks:
  greelogix-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
